listen:
- 127.0.0.1:8080
- "[::1]:8080"
vhosts:
  localhost:8080:
    default: true
    log_file: localhost.access.log
    log_format: [remote_addr, -, -, time_local, request, status, bytes_sent, http_referer, http_user_agent, processing_time]
    root: ../static-files-module/testdata/root
    canonicalize_uri: true
    index_file:
    - index.html
    compression_level_gzip: 3
    compression_level_brotli: 3
    compression_level_zstd: 3
    precompressed:
    - gz
    - br
    rewrite_rules:
    - from: /old.txt
      query_regex: "!noredirect"
      to: /file.txt
      type: permanent
    - from: /view.php
      query_regex: "^file=large\\.txt$"
      to: /large.txt
    - from: /images/*
      from_regex: "\\.jpg$"
      to: https://example.com${tail}
      type: redirect
    subpaths:
      /uncompressed/*:
        strip_prefix: true
        log_file: localhost.access.log
        root: ../static-files-module/testdata/root
        index_file:
        - index.html
      /reindexed/*:
        strip_prefix: true
        log_file: localhost.access.log
        root: ../static-files-module/testdata/root
        index_file:
        - file.txt
        canonicalize_uri: false
        compression_level_gzip: 3
        compression_level_brotli: 3
        compression_level_zstd: 3
        precompressed:
        - gz
        - br
